{"name": "删除批量创建而产生的部门", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败 -|- 实际结果:部门下有子部门或成员 || 预期结果: 成功", "trace": "cls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '210008', 'errmsg': '部门下有子部门或成员'}\nexpect_str = '{\"$.errmsg\":\"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools/data_process.py:118: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['case_046', '测试数据清理', '成员，部门相关', '删除批量创建而产生的部门', '/v1/dept/delete?access_token=&$.case_001.access_token&', '', ...]\n\n    @pytest.mark.flaky(reruns=0, reruns_delay=1)\n    def test_main(cases):#cases, get_db\n        # 此处的cases入参来自与 conftest.py  文件中 cases函数，与直接使用 @pytest.mark.parametrize\n        # 有着差不多的效果\n        # 发送请求\n        response, expect, sql = BaseRequest.send_request(cases)\n        # 执行sql\n        # DataProcess.handle_sql(sql, get_db)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest/test_api.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '210008', 'errmsg': '部门下有子部门或成员'}\nexpect_str = '{\"$.errmsg\":\"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(f'断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 断言失败 -|- 实际结果:部门下有子部门或成员 || 预期结果: 成功\n\ntools/data_process.py:120: AssertionError"}, "steps": [{"name": "请求地址", "status": "passed", "attachments": [{"name": "请求地址", "source": "32adff24-413b-4cfe-9535-788c547ffaf4-attachment.txt", "type": "text/plain"}], "start": 1616038000003, "stop": 1616038000003}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "46ae9ecc-97ac-49f7-96e5-575774823499-attachment.txt", "type": "text/plain"}], "start": 1616038000004, "stop": 1616038000004}, {"name": "请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "7adb903a-629c-458a-b366-9fcb92c75622-attachment.txt", "type": "text/plain"}], "start": 1616038000004, "stop": 1616038000004}, {"name": "上传文件", "status": "passed", "attachments": [{"name": "上传文件", "source": "62f7ebb7-76dd-4f01-873e-30e29cc2fc52-attachment.txt", "type": "text/plain"}], "start": 1616038000004, "stop": 1616038000004}, {"name": "响应耗时(s)", "status": "passed", "attachments": [{"name": "响应耗时(s)", "source": "b0159aaa-84ed-4fe8-906d-7a26928e069c-attachment.txt", "type": "text/plain"}], "start": 1616038000238, "stop": 1616038000238}, {"name": "响应内容", "status": "passed", "attachments": [{"name": "响应内容", "source": "3a4bb802-6908-44cc-a753-6780607a71b5-attachment.txt", "type": "text/plain"}], "start": 1616038000239, "stop": 1616038000239}, {"name": "存储实际响应", "status": "passed", "attachments": [{"name": "存储实际响应", "source": "5001735f-739a-424c-bc37-2f5e2652f63b-attachment.txt", "type": "text/plain"}], "start": 1616038000239, "stop": 1616038000240}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "f19bc61d-607e-4d7c-a8fa-f0130008ad0c-attachment.txt", "type": "text/plain"}], "start": 1616038000240, "stop": 1616038000241}], "parameters": [{"name": "cases", "value": "['case_046', '测试数据清理', '成员，部门相关', '删除批量创建而产生的部门', '/v1/dept/delete?access_token=&$.case_001.access_token&', '', 'get', 'params', '', '{\\n \"did\": \"&$.case_045.datas[1].did&\"\\n}', '', '', '{\"$.errmsg\":\"成功\"}']"}], "start": 1616038000003, "stop": 1616038000241, "uuid": "f0cc798a-109d-4e5d-a646-d9894809687e", "historyId": "7bd6a1d0f5bf41f56aee1bfbd64df136", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "tag", "value": "flaky(reruns=0, reruns_delay=1)"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "liuchengxudeMacBook-Pro.local"}, {"name": "thread", "value": "3455-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}