{"name": "发送一条新建的频道消息（应用6-应用已经被删除）", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败 -|- 实际结果:成功 || 预期结果: 应用信息验证失败", "trace": "cls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '0', 'errmsg': '成功', 'msgid': '6941234223877502488'}\nexpect_str = '{\"$.errmsg\":\"应用信息验证失败\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools/data_process.py:118: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['case_151', '消息中心应用消息', '发送消息', '发送一条新建的频道消息（应用6-应用已经被删除）', '/v1/message/send', '', ...]\n\n    @pytest.mark.flaky(reruns=0, reruns_delay=1)\n    def test_main(cases):#cases, get_db\n        # 此处的cases入参来自与 conftest.py  文件中 cases函数，与直接使用 @pytest.mark.parametrize\n        # 有着差不多的效果\n        # 发送请求\n        response, expect, sql = BaseRequest.send_request(cases)\n        # 执行sql\n        # DataProcess.handle_sql(sql, get_db)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest/test_api.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'tools.data_process.DataProcess'>\nresponse = {'errcode': '0', 'errmsg': '成功', 'msgid': '6941234223877502488'}\nexpect_str = '{\"$.errmsg\":\"应用信息验证失败\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(f'断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 断言失败 -|- 实际结果:成功 || 预期结果: 应用信息验证失败\n\ntools/data_process.py:120: AssertionError"}, "steps": [{"name": "请求地址", "status": "passed", "attachments": [{"name": "请求地址", "source": "fef07253-21f9-438b-a25d-fa9bdf66ec5a-attachment.txt", "type": "text/plain"}], "start": 1616132029505, "stop": 1616132029506}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "a4fbfcf5-74d4-4a9d-b80d-536f79ee00fe-attachment.txt", "type": "text/plain"}], "start": 1616132029506, "stop": 1616132029506}, {"name": "请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "676aac13-1ef6-46c2-817f-b9a5afb69f98-attachment.txt", "type": "text/plain"}], "start": 1616132029510, "stop": 1616132029511}, {"name": "上传文件", "status": "passed", "attachments": [{"name": "上传文件", "source": "db945c0c-1fef-4a33-ab38-541b9732b650-attachment.txt", "type": "text/plain"}], "start": 1616132029511, "stop": 1616132029511}, {"name": "响应耗时(s)", "status": "passed", "attachments": [{"name": "响应耗时(s)", "source": "a5f53244-75e2-4d9f-b7fd-f72cae54fdad-attachment.txt", "type": "text/plain"}], "start": 1616132029753, "stop": 1616132029754}, {"name": "响应内容", "status": "passed", "attachments": [{"name": "响应内容", "source": "16fab9ea-1739-471a-bbba-b0ba89aebab2-attachment.txt", "type": "text/plain"}], "start": 1616132029754, "stop": 1616132029754}, {"name": "存储实际响应", "status": "passed", "attachments": [{"name": "存储实际响应", "source": "3a9bd323-72fc-4d1c-b0a8-563c6db2c427-attachment.txt", "type": "text/plain"}], "start": 1616132029755, "stop": 1616132029761}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "614a341d-99ac-48b3-8753-9bbf37f86bae-attachment.txt", "type": "text/plain"}], "start": 1616132029762, "stop": 1616132029762}], "parameters": [{"name": "cases", "value": "['case_151', '消息中心应用消息', '发送消息', '发送一条新建的频道消息（应用6-应用已经被删除）', '/v1/message/send', '', 'post', 'json', '', '{\\n \"appid\": \"&$.test_023..datas[9].app_id&\",\\n \"access_token\": \"&$.case_100.access_token&\",\\n \"to_users\": [\"&$.test_010..datas[0].uid&\", \"&$.test_011..datas[0].uid&\", \"&$.test_004..datas[0].uid&\", \"&$.test_005..datas[0].uid&\"],\\n \"type\": \"text\",\\n \"message\": {\\n  \"content\": \"测试这个频道消息\"\\n },\\n \"msg_status\": \"1\"\\n}', '', '{\\n    \"errcode\": \"300002\",\\n    \"errmsg\": \"应用信息验证失败\"\\n}', '{\"$.errmsg\":\"应用信息验证失败\"}']"}], "start": 1616132029505, "stop": 1616132029762, "uuid": "a5adc97a-d9dd-475e-b4a7-eebf67fc6441", "historyId": "7b65bbbc1e21d0ef461ef1a6fe7d768b", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "tag", "value": "flaky(reruns=0, reruns_delay=1)"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "liuchengxudeMacBook-Pro.local"}, {"name": "thread", "value": "2415-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}